
3UBR0UTINt EXITT

C

c
c
c
10

c
c
c
c

20
)

EX
EX
EX
EX
THIS SUBROUTINE CALCULXTES THE BOUNDARY MCSH POINTS AT THE NOmE EX
EXIT EOR SUBSONIC FLON
EX
EX
* **t ****** ********t,*t******i,i,****
ex
EX
COMMON /AY/ IAV,CAV,NST,SMP,LSS,CTA,XMU,XLA,RKMU,8UT(BJ,2n,QVT(BlEX
J,2n,BPT(81,2n
Ex
COMMON /ONESID/ UO(=),VO(<(),POf#)ROO(=)
EX
Common /solutn/ U(si,2i,2),vfBi,2i,2),P(=i,2i,2)fR0(ei,2i,2)
ex
COMMON /CNTRLC/ LMAX,MMAX,NMAX,NPRINTTCONV,FDT,GAMMA,RGAS,GAM I, GAEX
JM2,L1*12L1M1,M2, DX,OY,DT>N,N1,NJ,NASM,IYEL*ICHAR,NIO.LJET,JFLAG,EX
2IERR,IUI,IUO,DXR,DYR,LD,MO,LMD1,LHDS,IB,RSTAR,RSTARS,NPLOT,G,PC,TCEX
J,LC,PLOH,ROLON
EX
COMMON /GEMTRYC/ NGEOM,XI,RI,XT,RT,XE,RE,RCI,RCT,ANGI,ANGE,XM(A1),EX
lYN(81),XWIcen,YWI<Sl),NXNY<BI),NNPTS,IINT,IDIF,LT,NDIM
EX
COMMON /GCB/ NGCB,XICB,RICB,XTCB,RTCB,XECB,RECB,RC1CB,RCTCB,ANGICBEX
t,ANGECB,XCB(An,YCB(Al),XCBI{en,YCBI(8I),NXNYCB(SI),NCBPT8,IINTCBEX
2,IDIFCB,LECB
EX
COMMON /BCC/ PT(2J),TT(2J),THETA(21),PE,MASSE,MASSI,MASST,THRUST, NEX
INSTAG
EX
REAL MNJ,NXNY,MASSI,MASST,NXNYCB,MASSE
EX
EX
XJXE
EX
ATERMI*0,0
EX
ATERM2*0.0
EX
ATERMJ*0,0
EX
DO 160 ICHAR=1,2
EX
DO 160 M J,MMAX
EX
CALL MAP (2,LMAX,M,AL,BE,DE,L1,AL1,BEI,DE1)
EX
Ul=U(LMAX,M,Nl)
ex
U2BU1
EX
Al>SORT(GAMMA*P(LMAX,M,Nl)/RO(LMAX,M,Nl))
ex
A2=A1
EX
IF (ICHAR,EO.2) GO TO 10
EX
U(LMAX,M,N3)*U1
EX
A3>A)
EX
EX
CALCULATE THE PROPERTY INTERPOLATING POLYNOMIAL COEFFICIENTS
EX
EX
BU=(U(LMAX,M,N1)U(L1,M,N1))A0XR
ex
BY*(V(LMAX,M,N1)-V(LI,M,N1))DXR
EX
BP=(P(LMAX,M,N1)-P(L1,M,N1))#DXR
ex
BRO=(RO(LMAX,M,NI)*R0(L1,M,N1))OXR
EX
BTCB=(YCB(LMAX)-YCB(L1))*DXR
EX
BAL=(AL-AL1)OXR
EX
BBE(BE*BE1)DXR
EX
