
SUBROUTINE CEOMCB

THIS SUBROUTINE CALCULATES THE CENTERBODY RADIUS AND SLOPE

DIMENSION YM(61)' NXNY(81)
COMMON /AV/ lAV'CAV'NST,3MP,LS8,CTA,XMU'XLA,RKMU'aUT(6W2l),C
ti2nraPT(st.?i)
COMMON /ONESID/ UDC=>,VDm,PDm,ROD(=)
COMMON /SOLUTN/ U(Bt21,2),V(6121,2)rP(B1 o 212)fRO(BW211 2)

J#LC,PLOH,ROLOW

e

r o o

m

--

o o r o r *

2. IDIPCB.LECB
COMMON /BCC/ PT<21)TT(21)#THETA(21)#PE
1STAG
REAL HN3,NXNYfMASS I(HASST*NXNYCB, MASSE

SB

ae

GO TO C1B'3B'|2B,16B)= NGCB
CYLINDRICAL CENTERBODY CASE
IF (lUI.EO.l) PRINT 2)0, X!CB,RICB,XECB
IF (IUI,EO,2) PRINT 240, XICB,RICB,XECB
LECB-LMAX
DO 20 !?!,LMAX
YCB(L)=RICB
NXNYCB(L)a0,0
CONTINUE
GO TO 200
CIRCULAR.ARC, CONICAL CENTERBODY CASE
XleXICB
RIaRICB
RT=RTCB
XEaXECB
RCIaRCICB
RCTaRCTCB
ANGIaANGICB
ANGEaANGECB
RIaJ,0*RT=RI
IF (RCI,EQt0.0,OR.BCT,EO,0,0) GO TO 190
AnJ=ANGI*)#|41)93/180.0
ANEaANGE*),141593/180,0
XTAN*XIaRCI*S1N(ANI)
RTANaRIvRCI*(COS(ANI).l,0)
RT|bRT.RCT(COS(ANI).1,0)
XTIbXTAN*(RT AN*R T1)/TAN(ANI)
IF (XTl.GE.XTAN) GO TO 40
XT 1aXT AN
RTlaRTAN
XTbXT1+RCT=SIN(ANI)
XTCBaXT
XT2XT+RCT=SIN(ANE)
RT2=RTtRCT*(1,0-COS(ANE))
Rt=RT2+(XE-XT2)*TAN(ANE)
RECBaRE
RIB2.0-RT-RI
REa2,0*RT-RE
IF (lUI.EO.l) PRINT 250, XI,RI,RT,XE,RCI,RCT,ANGI,ANGE,XT,RE
IF (IUI.E0.2) PRINT 260, XI,RI,RT,XE,RCI,RCT,ANGI,ANGE,XT,RE
RIB2.0-RT-RI
REa2,0*RT-RE
00 110 L1,LMAX
XaXI+(L-l)DX
IF (X.GE.XI.ANO.X.LE.XTAN) GO TO 50
IF (X.GT.XTAN.ANO.X.LE.XTl) GO TO 60
IF (X.GT.XTt.AND.X.LE.XT) GO TO 70
IF (X,GT,XT,AN0,X,LE,XT2) GO TO 80
IF (X.GT.XTB.AND.X.LE.XE) GO TO 90

c
SB
C

54

YM(L)RI*RCI=(COS(ASIN((X-XI)/RCI)).1.0)
NXNY(L)a(X*XI)/(YP(L)*RIRCI)
GO TO 100

GCB
GCB
GCB
rGCB
GCB
GCB
GCB
GCB
