
SUBROUTINE MAPUP,l,M,*LBEfOE,LOI,*U,BEl,DEH
O U O O O O (J

c

oo****o*=*o*o**=**=oooo*o***o*o*oo=**o**o**o**
this

subroutine

calculates

the

mappins functions

map

MAP
to***********************to****o=**o=*o*oo******o****

map

MAP
COMMON /AV/ TAV,CAV,NST,SMP,LSS,eTA,XMU,XLA,RKMU,0UT(61'2ntQVT(fllMAP
12I)=8PT(8|,?|)
MAP
COMMON /ONESID/ UD(4)>VD(=),PO(4)>ROD(A)
MAP
COMMON /SOLUTN/ U(fll21,?),V(81,21,2),P(R1,21,2),RO(81,21,?)
MAP
COMMON /CNTRLC/ LMAXMMAX,NMAX,NPRI NT,TCONV,EOT,GAMMA,RSAS,GANI,GAMAP
lM2,LI,L2,LS,Ml,M2,0X,DY,DT,N,Nt,NS,NASM,IVEL,1CHAR,N1D,LJET,JFLAG,MAP
21ERR,IUI,IUO,DXR,DVR,LD,MD,LMDt,LM03,IB,RSTAR,RSTARS,NPLOT,G,PC,TCMAP
3,LC,PLOW,ROLOM
MAP
common /GEMTRYC/ NGEOM,XI,Rl,XT,RT,XE,RE,RCI,RCT,ANGI,ANGE,XN(81),MAP
1YH(8!),XWI(81),YNI(8!),NXNY(81),NMPTS,IINT,IDIF,LT,NO1M
MAP
COMMON /GCB/ NGCB,XICB,RICB,XTCB,RTCB,XECB,RECB,RCICB,RCTCB,ANGICBMAP
t,ANGECB,XCB(8n,YCB(8t),XCBI(ei),YCBI(81),NXNYCB(Bn,NCBPTS, IINTCBMAP
2,IDIFCB,LECB
MAP
COMMON /BCC/ PT(21),TT(21),THETA(2i),PE,MASSE,MASS I,MASST, THRUST, NMAP
1ST AG
MAP
REAL MN3,NXNY,MASSI,MASST,NXNYCB,MASSE
MAP
MAP
be=i,0/(yn(l)'Ycb(L))
map
IF (IP,EO.B) RETURN
Y(M1)0Y
AL=BE*(NXNYCB(L)AY*(NXNY(L)*NXNYCB(L))>

62

MAP
MAP
MAP
MAP

MAP
MAP
MAP

DEb>BE*Y*XHI(L)

map

IF (IP.EO.l) RETURN
BEI|,0/(YN(LD1)*YCB(LD)))
ALIiBEl*(NXNYCB(LDl)*Y*(NXNY(LD|)=NXNYCB(LDl)n
DElB=BEt*Y*XMI(LOn
RETURN
END
