      SUBROUTINE MTLUP (X,Y,M,N,MAX,NTAB,I,VARI,VARD)
C
C     THIS SUBROUTINE IS CALLED BY SUBROUTINE GEOM TO INTERPOLATE FOR
C     EQUALLY SPACED NOZZLE WALL COORDINATES FOR THE TABULAR INPUT CASE.
C     SUBROUTINE MTLUP WAS TAKEN FROM THE NASA-LANGLEY PROGRAM LIBRARY.
C
C     MODIFICATION OF LIBRARY INTERPOLATION SUBROUTINE FTLUP
C     MULTIPLE TABLE LOOK-UP ON ONE INDEPENDENT VARIABLE TABLE
C     USES AN EXTERNAL INTERVAL POINTER (I) TO START SEARCH
C     I LESS THAN 0 WILL CHECK MONOTONICITY
C
C     OCR note:
C     Reconstructed from Appendix C listing text blocks. Some original
C     diagnostic text literals were normalized where the scan was unreadable.
C     Diagnostic FORMAT wording is normalized for readability.
C
      DIMENSION VARI(N),VARD(MAX,1),Y(1),V(3),YY(2)
      LOGICAL EX
C
      IF (M.EQ.0) GO TO 170
      IF (N.LE.1) GO TO 170
      EX=.FALSE.
      IF (I.GE.0) GO TO 60
      IF (N.LT.2) GO TO 60
C
C     MONOTONICITY CHECK
C
      IF (VARI(2)-VARI(1)) 20,20,40
C
C     ERROR IN MONOTONICITY
C
10    PRINT 190, N
      STOP
C
C     MONOTONIC DECREASING
C
20    DO 30 J=2,N
      IF (VARI(J)-VARI(J-1)) 30,10,10
30    CONTINUE
      GO TO 60
C
C     MONOTONIC INCREASING
C
40    DO 50 J=2,N
      IF (VARI(J)-VARI(J-1)) 10,10,50
50    CONTINUE
C
C     INTERPOLATION
C
60    IF (I.LE.0) I=1
      IF (I.GE.N) I=N-1
C
C     LOCATE I INTERVAL (VARI(I) .LE. X .LT. VARI(I+1))
C
      IF ((VARI(I)-X)*(VARI(I+1)-X)) 100,100,70
C
C     IN GIVES DIRECTION FOR SEARCH OF INTERVALS
C
70    IN=SIGN(1.0,(VARI(N)-VARI(I))*(X-VARI(I)))
C
C     IF X OUTSIDE ENDPOINTS, EXTRAPOLATE FROM END INTERVAL
C
80    IF ((I+IN).LE.0) GO TO 90
      IF ((I+IN).GE.N) GO TO 90
      I=I+IN
      IF ((VARI(I)-X)*(VARI(I+1)-X)) 100,100,80
C
C     EXTRAPOLATION
C
90    EX=.TRUE.
100   IF (M.EQ.2) GO TO 120
C
C     FIRST ORDER
C
      DO 110 NT=1,NTAB
110   Y(NT)=(VARD(I,NT)*(VARI(I+1)-X)-VARD(I+1,NT)*(VARI(I)-X))/
     1 (VARI(I+1)-VARI(I))
      IF (EX) I=I-IN
      RETURN
C
C     SECOND ORDER
C
120   IF (N.EQ.2) GO TO 110
      IF (I.EQ.(N-1)) GO TO 140
      IF (I.EQ.1) GO TO 130
C
C     PICK THIRD POINT
C
      SK=VARI(I+1)-VARI(I)
      IF (ABS(X-VARI(I+1)).LT.ABS(VARI(I+2)-X)) GO TO 140
130   L=I
      GO TO 150
140   L=I-1
150   V(1)=VARI(L)-X
      V(2)=VARI(L+1)-X
      V(3)=VARI(L+2)-X
      DO 160 NT=1,NTAB
      YY(1)=(VARD(L,NT)*V(2)-VARD(L+1,NT)*V(1))/(VARI(L+1)-VARI(L))
      YY(2)=(VARD(L+1,NT)*V(3)-VARD(L+2,NT)*V(2))/(VARI(L+2)-VARI(L+1))
160   Y(NT)=(YY(1)*V(3)-YY(2)*V(1))/(VARI(L+2)-VARI(L))
      IF (EX) I=I-IN
      RETURN
C
C     ZERO ORDER
C
170   DO 180 NT=1,NTAB
180   Y(NT)=VARD(I,NT)
      RETURN
C
190   FORMAT (1H1,49H TABLE BELOW OUT OF ORDER FOR MTLUP, N = ,I5)
      END
