      SUBROUTINE SHOCK(IPASS)
C
C     **************************************************************
C     THIS SUBROUTINE CALCULATES THE LOCAL ARTIFICAL VISCOSITY TERMS
C     FOR SHOCK COMPUTATIONS
C     **************************************************************
C
C     OCR note:
C     Reconstructed from Appendix C PDF text blocks and aligned to
C     Appendix C line blocks for the viscosity-energy term structure.
C
      COMMON /AV/ IAV,CAV,NST,SMP,LSS,CTA,XMU,XLA,RKMU,QUT(81,21),QVT(81,21),QPT(81,21)
      COMMON /ONESID/ UD(4),VD(4),PD(4),ROD(4)
      COMMON /SOLUTN/ U(81,21,2),V(81,21,2),P(81,21,2),RO(81,21,2)
      COMMON /CNTRLC/ LMAX,MMAX,NMAX,NPRINT,TCONV,FDT,GAMMA,RGAS,GAM1,GAM2,
     1L1,L2,L3,M1,M2,DX,DY,DT,N,N1,N3,NASM,IVEL,ICHAR,N1D,LJET,JFLAG,
     2IERR,IUI,IUO,DXR,DYR,LD,MD,LMD1,LMD3,IB,RSTAR,RSTARS,NPLOT,G,PC,TC,
     3LC,PLOW,ROLOW
      COMMON /GEMTRYC/ NGEOM,XI,RI,XT,RT,XE,RE,RCI,RCT,ANGI,ANGE,XW(81),
     1YW(81),XWI(81),YWI(81),NXNY(81),NWPTS,IINT,IDIF,LT,NDIM
      COMMON /GCB/ NGCB,XICB,RICB,XTCB,RTCB,XECB,RECB,RCICB,RCTCB,ANGICB,
     1ANGECB,XCB(81),YCB(81),XCBI(81),YCBI(81),NXNYCB(81),NCBPTS,IINTCB,
     2IDIFCB,LECB
      COMMON /BCC/ PT(21),TT(21),THETA(21),PE,MASSE,MASSI,MASST,THRUST,
     1NSTAG
      REAL MN3,NXNY,MASSI,MASST,NXNYCB,MASSE
C
      GO TO (10,160), IPASS
C
C     CALCULATE LOCAL ARTIFICAL VISCOSITY FOR SHOCK COMPUTATIONS
C
10    IF (N.NE.1) GO TO 30
      NC=0
      RG=RGAS*G
      CTA1=1.0-CTA
      DO 20 L=1,LMAX
      DO 20 M=1,MMAX
      QUT(L,M)=0.0
      QVT(L,M)=0.0
      QPT(L,M)=0.0
20    CONTINUE
30    RDUM=CAV*DT*DX*DY*2.0
      NC=NC+1
      NLINE=0
      IF (NC.NE.NPRINT) GO TO 40
      PRINT 200
      PRINT 190, N, PC
C
40    DO 150 L=LSS,L1
      DO 150 M=1,MMAX
      LMD2=LD*(M-1)+LMD1
      LMMD2=LD*(M-2)+LMD1
      LMPD2=LD*M+LMD1
      LMN1=L+LMD2
      LP=L+1+LMD2
      LM=L-1+LMD2
      MP=L+LMPD2
      MM=L+LMMD2
      LPMP=L+1+LMPD2
      LPMM=L+1+LMMD2
      LMMP=L-1+LMPD2
      LMMM=L-1+LMMD2
      CALL MAP (1,L,M,AL,BE,DE,LD1,AL1,BE1,DE1)
C
C     CHECK TO SEE IF THE DIVERGENCE OF THE VELOCITY IS NEGATIVE
C
      UX=0.5*(U(LP)-U(LM))*DXR
      IF (M.EQ.1) GO TO 50
      IF (M.EQ.MMAX) GO TO 60
      UY=0.5*(U(MP)-U(MM))*DYR
      VY=0.5*(V(MP)-V(MM))*DYR
      GO TO 70
50    UY=(U(MP)-U(LMN1))*DYR
      VY=(V(MP)-V(LMN1))*DYR
      GO TO 70
60    UY=(U(LMN1)-U(MM))*DYR
      VY=(V(LMN1)-V(MM))*DYR
70    DIV=UX+AL*UY+BE*VY
      IF (DIV.LT.0.0) GO TO 80
      QUT(L,M)=0.0
      QVT(L,M)=0.0
      QPT(L,M)=0.0
      GO TO 150
C
80    OQUT=QUT(L,M)
      OQVT=QVT(L,M)
      OQPT=QPT(L,M)

      UX1=(U(LMN1)-U(LM))*DXR
      UX2=(U(LP)-U(LMN1))*DXR
      VX1=(V(LMN1)-V(LM))*DXR
      VX2=(V(LP)-V(LMN1))*DXR
      TM=P(LM)/(RO(LM)*RG)
      T=P(LMN1)/(RO(LMN1)*RG)
      TP=P(LP)/(RO(LP)*RG)
      TX1=(T-TM)*DXR
      TX2=(TP-T)*DXR

      LDUM=L-1
      CALL MAP (1,LDUM,M,ALM,BEM,DE,LD1,AL1,BE1,DE1)
      LDUM=L+1
      CALL MAP (1,LDUM,M,ALP,BEP,DE,LD1,AL1,BE1,DE1)
      BE1=0.5*(BEM+BE)
      BE2=0.5*(BEP+BE)
      AL1=0.5*(ALM+AL)
      AL2=0.5*(ALP+AL)

      IF (M.EQ.1) GO TO 90
      IF (M.EQ.MMAX) GO TO 100
C
C     CALCULATE THE INTERIOR POINT QUANTITIES
C
      UY1=0.25*(U(MP)+U(LMMP)-U(MM)-U(LMMM))*DYR
      UY2=0.25*(U(MP)+U(LPMP)-U(MM)-U(LPMM))*DYR
      VY1=0.25*(V(MP)+V(LMMP)-V(MM)-V(LMMM))*DYR
      VY2=0.25*(V(MP)+V(LPMP)-V(MM)-V(LPMM))*DYR
      UX3=0.25*(U(LP)+U(LPMM)-U(LM)-U(LMMM))*DXR
      UX4=0.25*(U(LP)+U(LPMP)-U(LM)-U(LMMP))*DXR
      VX3=0.25*(V(LP)+V(LPMM)-V(LM)-V(LMMM))*DXR
      VX4=0.25*(V(LP)+V(LPMP)-V(LM)-V(LMMP))*DXR
      VY3=(V(LMN1)-V(MM))*DYR
      VY4=(V(MP)-V(LMN1))*DYR
      UY3=(U(LMN1)-U(MM))*DYR
      UY4=(U(MP)-U(LMN1))*DYR

      TMY=P(MM)/(RO(MM)*RG)
      TPY=P(MP)/(RO(MP)*RG)
      TMM=P(LMMM)/(RO(LMMM)*RG)
      TMP=P(LMMP)/(RO(LMMP)*RG)
      TPM=P(LPMM)/(RO(LPMM)*RG)
      TPP=P(LPMP)/(RO(LPMP)*RG)
      TY1=0.25*(TPY+TMP-TMY-TMM)*DYR
      TY2=0.25*(TPP+TPY-TPM-TMY)*DYR
      TX3=0.25*(TP+TPM-TM-TMM)*DXR
      TX4=0.25*(TPP+TP-TMP-TM)*DXR
      TY3=(T-TMY)*DYR
      TY4=(TPY-T)*DYR

      MDUM=M-1
      CALL MAP (1,L,MDUM,ALMY,BEMY,DE,LD1,AL1,BE1,DE1)
      MDUM=M+1
      CALL MAP (1,L,MDUM,ALPY,BEPY,DE,LD1,AL1,BE1,DE1)
      BE3=0.5*(BEMY+BE)
      BE4=0.5*(BEPY+BE)
      AL3=0.5*(ALMY+AL)
      AL4=0.5*(ALPY+AL)
      GO TO 110
C
C     CALCULATE THE CENTERLINE POINT QUANTITIES
C
90    UY1=0.5*(U(MP)+U(LMMP)-U(LMN1)-U(LM))*DYR
      VY1=0.5*(V(MP)+V(LMMP)-V(LMN1)-V(LM))*DYR
      UY2=0.5*(U(LPMP)+U(MP)-U(LP)-U(LMN1))*DYR
      VY2=0.5*(V(LPMP)+V(MP)-V(LP)-V(LMN1))*DYR
      UX3=0.0
      VX3=0.0
      UX4=0.0
      VX4=0.0
      THEW=ATAN(-NXNYCB(L))
      THE=ATAN(V(MP)/U(MP))
      VMAG=SQRT(U(MP)*U(MP)+V(MP)*V(MP))
      RTHE=2.0*THEW-THE
      UR=VMAG*COS(RTHE)
      VR=VMAG*SIN(RTHE)
      UY3=(U(LMN1)-UR)*DYR
      VY3=(V(LMN1)-VR)*DYR
      UY4=(U(MP)-U(LMN1))*DYR
      VY4=(V(MP)-V(LMN1))*DYR
      TPY=P(MP)/(RO(MP)*RG)
      TMP=P(LMMP)/(RO(LMMP)*RG)
      TPP=P(LPMP)/(RO(LPMP)*RG)
      TY1=0.0
      TY2=0.0
      TX3=0.25*(TPP+TP-TMP-TM)*DXR
      TX4=TX3
      TY4=(TPY-T)*DYR
      TY3=-TY4
      BE3=BE
      AL3=AL
      MDUM=M+1
      CALL MAP (1,L,MDUM,AL4,BE4,DE,LD1,AL1,BE1,DE1)
      GO TO 110
C
C     CALCULATE THE WALL POINT QUANTITIES
C
100   UY1=0.5*(U(LMN1)+U(LM)-U(MM)-U(LMMM))*DYR
      VY1=0.5*(V(LMN1)+V(LM)-V(MM)-V(LMMM))*DYR
      UY2=0.5*(U(LP)+U(LMN1)-U(LPMM)-U(MM))*DYR
      VY2=0.5*(V(LP)+V(LMN1)-V(LPMM)-V(MM))*DYR
      UX3=0.0
      VX3=0.0
      UX4=0.0
      VX4=0.0
      UY3=(U(LMN1)-U(MM))*DYR
      VY3=(V(LMN1)-V(MM))*DYR
      THEW=ATAN(-NXNY(L))
      THE=ATAN(V(MM)/U(MM))
      VMAG=SQRT(U(MM)*U(MM)+V(MM)*V(MM))
      RTHE=2.0*THEW-THE
      UR=VMAG*COS(RTHE)
      VR=VMAG*SIN(RTHE)
      UY4=(UR-U(LMN1))*DYR
      VY4=(VR-V(LMN1))*DYR
      TPM=P(LPMM)/(RO(LPMM)*RG)
      TMY=P(MM)/(RO(MM)*RG)
      TMM=P(LMMM)/(RO(LMMM)*RG)
      TY1=0.0
      TY2=0.0
      TX3=0.25*(TP+TPM-TM-TMM)*DXR
      TX4=TX3
      TY3=(T-TMY)*DYR
      TY4=-TY3
      MDUM=M-1
      CALL MAP (1,L,MDUM,AL3,BE3,DE,LD1,AL1,BE1,DE1)
      BE4=BE
      AL4=AL
C
110   UXY1=UX1+AL1*UY1
      UXY2=UX2+AL2*UY2
      UXY3=UX3+AL3*UY3
      UXY4=UX4+AL4*UY4
      UXY12=0.5*(UX1+UX2+AL3*UY3+AL4*UY4)

      VXY1=VX1+AL1*VY1
      VXY2=VX2+AL2*VY2
      VXY3=VX3+AL3*VY3
      VXY4=VX4+AL4*VY4
      VXY12=0.5*(VX1+VX2+AL3*VY3+AL4*VY4)

      BUY1=BE1*UY1
      BUY2=BE2*UY2
      BUY3=BE3*UY3
      BUY4=BE4*UY4
      BUY34=0.5*(BUY3+BUY4)

      BVY1=BE1*VY1
      BVY2=BE2*VY2
      BVY3=BE3*VY3
      BVY4=BE4*VY4
      BVY34=0.5*(BVY3+BVY4)

      TXY1=TX1+AL1*TY1
      TXY2=TX2+AL2*TY2
      TXY3=TX3+AL3*TY3
      TXY4=TX4+AL4*TY4
C
C     CALCULATE THE ARTIFICAL VISCOSITY COEFFICIENTS
C
      DIV=UXY12+BVY34
      VID=VXY12-BUY34
      RLA=XLA*RDUM*ABS(DIV)/BE
      RMU=XMU*RDUM*ABS(VID)/BE
      RK=RMU*GAM1*RG/RKMU
      RLP2M=RLA+2.0*RMU
      RLA2=2.0*RLA
      RMU2=2.0*RMU
      RLPM=RLA+RMU
      UVTA=0.0
      VVTA=0.0
      PVTA=0.0
      PCTA=0.0

      IF (NDIM.EQ.0) GO TO 130
C
C     CALCULATE THE AXISYMMETRIC TERMS
C
      IF (M.EQ.1.AND.YCB(L).EQ.0.0) GO TO 120
      Y=FLOAT(M-1)*DY/BE+YCB(L)
      VB=V(LMN1)
      UVTA=(RLPM*VXY12+RMU*BUY34)/Y
      VVTA=RLP2M*(BVY34+VB/Y)/Y
      PVTA=(RLP2M*VB*VB/Y+RLA2*VB*(BVY34+UXY12))/Y
      PCTA=RK*0.5*(BE4*TY4+BE3*TY3)/Y
      DUVTA=RLPM*BE*(VXY4-VXY3)*DYR+RMU*BE*(BUY4-BUY3)*DYR
      DVVTA=RLP2M*0.5*BE*(BVY4-BVY3)*DYR
      DPVTA=(RLP2M+RLA2)*BVY34*BVY34+RLA2*BVY34*UXY12
      DPCTA=RK*BE*(BE4*TY4-BE3*TY3)*DYR
      IF (ABS(UVTA).GT.ABS(DUVTA)) UVTA=DUVTA
      IF (ABS(VVTA).GT.ABS(DVVTA)) VVTA=DVVTA
      IF (ABS(PVTA).GT.ABS(DPVTA)) PVTA=DPVTA
      IF (ABS(PCTA).GT.ABS(DPCTA)) PCTA=DPCTA
      GO TO 130
120   UVTA=RLPM*BE*(VXY4-VXY3)*DYR+RMU*BE*(BUY4-BUY3)*DYR
      VVTA=RLP2M*0.5*BE*(BVY4-BVY3)*DYR
      PVTA=(RLP2M+RLA2)*BVY34*BVY34+RLA2*BVY34*UXY12
      PCTA=RK*BE*(BE4*TY4-BE3*TY3)*DYR
C
C     CALCULATE THE ARTIFICAL VISCOSITY TERMS
C
130   QUT(L,M)=RLP2M*(UXY2-UXY1)*DXR
     1 + AL*(RLP2M*(UXY4-UXY3)+RLA*(BVY4-BVY3))*DYR
     2 + RMU*BE*(VXY4-BUY4-VXY3+BUY3)*DYR + UVTA

      QVT(L,M)=RMU*(VXY2-BUY2-VXY1+BUY1)*DXR
     1 + RMU*AL*(VXY4-BUY4-VXY3+BUY3)*DYR
     2 + BE*(RLA*(UXY4-UXY3)+RLP2M*(BVY4-BVY3))*DYR + VVTA

      QPT(L,M)=RO(LMN1)*(GAMMA-1.0)*
     1 (RLP2M*(UXY12*UXY12+BVY34*BVY34)
     2 + RMU*(VXY12*VXY12+BUY34*BUY34)
     3 + RLA2*UXY12*BVY34 + RMU2*BUY34*VXY12
     4 + RK*((TXY2-TXY1)*DXR + AL*(TXY4-TXY3)*DYR
     5 + BE*(BE4*TY4-BE3*TY3)*DYR) + PVTA + PCTA)

      QUT(L,M)=CTA*QUT(L,M)+CTA1*OQUT
      QVT(L,M)=CTA*QVT(L,M)+CTA1*OQVT
      QPT(L,M)=CTA*QPT(L,M)+CTA1*OQPT

      IF (NC.NE.NPRINT) GO TO 150
      NLINE=NLINE+1
      IF (NLINE.LT.55) GO TO 140
      PRINT 200
      PRINT 190, N, PC
      NLINE=1
140   QPT(L,M)=QPT(L,M)/PC
      PRINT 180, L,M,QUT(L,M),QVT(L,M),QPT(L,M)
      QPT(L,M)=QPT(L,M)*PC
150   CONTINUE

      IF (NC.EQ.NPRINT) NC=0
      RETURN
C
C     SMOOTH THE FLOW VARIABLES IF REQUESTED
C
160   IF (SMP.LT.0.0.OR.SMP.GE.1.0) RETURN
      SMP4=0.25*(1.0-SMP)
      DO 170 L=2,L1
      U(L,MMAX,N3)=SMP4*(U(L-1,MMAX,N3)+U(L+1,MMAX,N3)+2.0*U(L,M1,N3))
     1 +SMP*U(L,MMAX,N3)
      V(L,MMAX,N3)=-U(L,MMAX,N3)*NXNY(L)
      P(L,MMAX,N3)=SMP4*(P(L-1,MMAX,N3)+P(L+1,MMAX,N3)+2.0*P(L,M1,N3))
     1 +SMP*P(L,MMAX,N3)
      RO(L,MMAX,N3)=SMP4*(RO(L-1,MMAX,N3)+RO(L+1,MMAX,N3)+2.0*RO(L,M1,N3))
     1 +SMP*RO(L,MMAX,N3)

      U(L,1,N3)=SMP4*(U(L-1,1,N3)+U(L+1,1,N3)+2.0*U(L,2,N3))
     1 +SMP*U(L,1,N3)
      V(L,1,N3)=-U(L,1,N3)*NXNYCB(L)
      P(L,1,N3)=SMP4*(P(L-1,1,N3)+P(L+1,1,N3)+2.0*P(L,2,N3))
     1 +SMP*P(L,1,N3)
      RO(L,1,N3)=SMP4*(RO(L-1,1,N3)+RO(L+1,1,N3)+2.0*RO(L,2,N3))
     1 +SMP*RO(L,1,N3)

      DO 170 M=2,M1
      LMD2=LD*(M-1)+LMD3
      LMMD2=LD*(M-2)+LMD3
      LMPD2=LD*M+LMD3
      LMN3=L+LMD2
      LP=L+1+LMD2
      LM=L-1+LMD2
      MP=L+LMPD2
      MM=L+LMMD2
      U(LMN3)=SMP4*(U(LM)+U(LP)+U(MM)+U(MP))+SMP*U(LMN3)
      V(LMN3)=SMP4*(V(LM)+V(LP)+V(MM)+V(MP))+SMP*V(LMN3)
      P(LMN3)=SMP4*(P(LM)+P(LP)+P(MM)+P(MP))+SMP*P(LMN3)
      RO(LMN3)=SMP4*(RO(LM)+RO(LP)+RO(MM)+RO(MP))+SMP*RO(LMN3)
170   CONTINUE

      RETURN
180   FORMAT (1H ,5X,2I5,3F18.8)
190   FORMAT (1H0,63HLOCAL ARTIFICAL VISCOSITY PARAMETERS FOR SHOCK CALC,
     1ULATIONS, N=,I4,5H (PC=,F5.1,1H),/,/,10X,1HL,4X,1HM,10X,3HQUT,
     2 11X,3HQVT,11X,3HQPT,/)
200   FORMAT (1H1)
      END
